### ISSUE TITLE
can you make a seccond game of this???

### ISSUE THREAD

**Issue by sebby09559** [ninjamuffin99/RITZ#21]
or you can't??????

**Comment by ThePlank** [comment]
This is not Dani. Also Ritz DX got cancelled already.

**Comment by MrClogsworthYT** [comment]
> This is not Dani. Also Ritz DX got cancelled already.

atleast ritz will be in fnf

**Comment by GDasdf** [comment]
how do you know he'l be in fnf?

**Comment by GDasdf** [comment]
also this isnt an issue

**Comment by upintheairsheep** [comment]
http://fridaynightfunkin.fandom.com/wiki/Ritz

**Comment by upintheairsheep** [comment]
Close this issue.
